# Generated by Django 4.1.3 on 2024-06-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.CharField(max_length=255),
        ),
    ]
